/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <stdio.h>
#include <assert.h>

#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, "keymatch", __VA_ARGS__)
/* Header for class com_bric_kagdatabkt_utils_JNIUtil */

/*
 * Class:     com_bric_kagdatabkt_utils_JNIUtil
 * Method:    showHelloWord
 * Signature: ()V
 */
/**
JNIEXPORT void JNICALL Java_com_bric_kagdatabkt_utils_JNIUtil_showHelloWord
        (JNIEnv *env, jobject obj) {
    LOGD("我要看到的调试信息^_^");
}
*/

void showHelloWord(JNIEnv *env, jclass clazz, jstring content) {
    char buf[32];
    const char *str = (*env)->GetStringUTFChars(env, content, 0);
    LOGD("我要看到的调试信息^_^%s", str);
    (*env)->ReleaseStringChars(env, content, str);
}

int native_test3(JNIEnv *env, jclass clazz, int i, int j) {
    LOGD("我要看到的调试信息^_^i=%d", i);
    LOGD("我要看到的调试信息^_^j=%d", j);
    return i + 1;
}

JNINativeMethod method[] = {{"testAdd",       "(II)I",                 (int *) native_test3},
                            {"showHelloWord", "(Ljava/lang/String;)V", (int *) showHelloWord}};
//JNINativeMethod method[] = {{"", "", (int *) testAdd},
//                            {"", "", (int *) showHelloWord}};
//替换java端的test3


static int registerNativeMethods(JNIEnv *env, const char *className, JNINativeMethod *gMethods,
                                 int numMethods) {
    jclass clazz;
    clazz = (*env)->FindClass(env, className);
    if (clazz == NULL) {
        return JNI_FALSE;
    }
    if ((*env)->RegisterNatives(env, clazz, gMethods, numMethods) < 0) {
        return JNI_FALSE;
    }
    return JNI_TRUE;
}

static int registerNatives(JNIEnv *env) {
    const char *kClassName = "com/bric/kagdatabkt/utils/JNIUtil";//指定要注册的类
    return registerNativeMethods(env, kClassName, method,
                                 sizeof(method) / sizeof(method[0]));
}

/*
* System.loadLibrary("lib")时调用
* 如果成功返回JNI版本, 失败返回-1
*/
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    JNIEnv *env = NULL;
    jint result = -1;
    if ((*vm)->GetEnv(vm, (void **) &env, JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }
    assert(env != NULL);
    if (!registerNatives(env)) {//注册
        return -1;
    }
    //成功
    result = JNI_VERSION_1_6;
    return result;
}

