/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bric_kagdatabkt_utils_JNIUtil */

#ifndef _Included_com_bric_kagdatabkt_utils_JNIUtil
#define _Included_com_bric_kagdatabkt_utils_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bric_kagdatabkt_utils_JNIUtil
 * Method:    showHelloWord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bric_kagdatabkt_utils_JNIUtil_showHelloWord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
